### ISSUE TITLE
stylesheets without href

### ISSUE THREAD

**Issue by nicholi** [EmberConsultingGroup/StyleBundleFallback#1]
Noticed I had a few stylesheets on page which have null href property, causing the sheet.href.indexOf() call to raise an exception. Just made simple modification to

`if (sheet.href && sheet.href.indexOf('{0}') !== -1) {{`

The stylesheets were from manually injected 3rd party libs (like Typekit), guessing it didn't create all properties? Might be browser specific, only tested on Chrome.

**Comment by akonyer** [comment]
Yes I have this issue as well. This fix does work.
